# Generated by Django 5.1.6 on 2025-03-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Cell',
        ),
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.CharField(default=27717644735, max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='Message',
            field=models.TextField(max_length=200),
        ),
    ]
